update create bash script

diff --git a/scripts/create-bash-script b/scripts/create-bash-script
--- a/scripts/create-bash-script
+++ b/scripts/create-bash-script
@@ -6,5 +6,16 @@ if [[ -z "$1" ]]; then
     echo -e "\t$0 your file name"
     exit
 fi
-echo '#!/bin/bash' > "$1"
+
+SCRIPT=$(cat <<-EOF
+#!/bin/bash
+
+set -o errexit  # exit if non-zero status code is returned
+set -o nounset  # exit if undefined variable is used
+set -o pipefail # exit if no-zero status code is returned in a pipeline
+IFS=$'\\\n\\\t'
+EOF
+)
+
+echo -e "$SCRIPT" > "$1"
 chmod +x "$1"
