feat: keg integrated with tab completion
Moved away from using zet and instead use keg `**<tab>` for finding
things.  The advantage of this approach is that searching for things
goes in to the history

diff --git a/home/scripts/_keg-node-complete b/home/scripts/_keg-node-complete
--- a/home/scripts/_keg-node-complete
+++ b/home/scripts/_keg-node-complete
@@ -1,18 +1,20 @@
 #!/bin/bash
 
+set -o errexit  # exit if non-zero status code is returned
+set -o nounset  # exit if undefined variable is used
+set -o pipefail # exit if no-zero status code is returned in a pipeline
+IFS=$'\n\t'
+
 # RG_PREFIX='rg --color=always --line-number --files --no-heading --smart-case --glob "docs/**/README.md"'
 RG_PREFIX='_keg-node-search'
 INITIAL_QUERY=""
+FILES="$@"
+echo $FILES > /tmp/files
 # shellcheck disable=SC2034
 FZF_DEFAULT_COMMAND="$RG_PREFIX '$INITIAL_QUERY'"
 fzf \
     --bind "change:reload:$RG_PREFIX {q} || true" \
-    --bind "enter:become($EDITOR docs/{1}/README.md && CHOICE={1})" \
     --sort \
-    --delimiter ':' \
-    --with-nth '1,2' \
     --preview 'echo -n {1} " "; rg "^#" docs/{1}/README.md --no-heading | head -n 1;bat --style "grid,numbers,snip" --color=always --paging never docs/{1}/README.md' \
-    --preview-window 'right,90%' \
-    --ansi --phony --query "$INITIAL_QUERY"
+    --ansi --phony --query "$INITIAL_QUERY" "$@"
 
-echo "$CHOICE"
